import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        marginTop:30,
        justifyContent:'space-evenly'
    },
    headContainer:{
        flexDirection:'row',
        justifyContent:'center',
        position:'relative',
        marginHorizontal:10
    },
    leftArrow:{
        width:32,
        height:32,
        borderRadius:16,
        backgroundColor:'#EAEDFB',
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        left:0
    },
    pCircle:{
        width:32,
        height:32,
        borderRadius:16,
        backgroundColor:'#EAEDFB',
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        right:10,
        borderWidth:1,
        borderColor:'rgba(34, 66, 216, 0.5)'
    },
    headTxt:{
        color:'#2242D8',
        fontSize:20,
        fontWeight:'bold',
    },
    searchContainer:{
        width:'80%',
        height:50,
        backgroundColor:'#EAEDFB',
        borderRadius:20,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    connectionCont:{
        width:50,
        height:50,
        backgroundColor:'#EAEDFB',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:20
    },
    searchMainCont:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginHorizontal:18,
        marginVertical:10
    },
    circle:{
        width:22,
        height:22,
        position:'absolute',
        left:20
    },
    contactContainer:{
        flexDirection:'row',
        backgroundColor:'#EAEDFB',
        width:'80%',
        height:60,
        alignItems:'center',
        borderRadius:20,
        position:'relative',
        marginLeft:20,
        marginVertical:5
    },
    nameTxt:{
        fontSize:14,
        fontWeight:'bold',
        color:'#2242D8',
    },
    nameContainer:{
        position:'absolute',
        left:70
    },
    desTxt:{
        fontSize:10,
        fontWeight:'bold',
        color:'#7085E6',
    },
    contactImg:{
        width:38,
        height:38,
        position:'absolute',
        left:15
    },
    viewContainer:{
        width:55,
        height:25,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#ffff',
        borderWidth:1,
        borderRadius:20,
        borderColor:'#2242D8',
        position:'absolute',
        right:15
    },
    viewTxt:{
        fontSize:12,
        color:'#2242D8',
        fontWeight:'400'
    },
    headerTxtContainer:{
        width:35,
        height:35,
        backgroundColor:'#EAEDFB',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:16,
        marginLeft:20
    },
    headerTxt:{
        color:'#2242D8',
        fontWeight:'bold',
        fontSize:16
    },
    sideSteper:{
        width:21,
        height:226,
        backgroundColor:'#EAEDFB',
        borderRadius:20,
        position:'absolute',
        alignItems:'center',
        right:10,
        top:280
    },
    steperTxt:{
        color:'#2242D8',
        fontSize:12,
        fontWeight:'400',
        marginVertical:4
    }
})

export default styles;